services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./mariadb
    image: mariadb:notlatest
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"
  
  nginx:
  container_name: nginx
  networks:
    - inception
  depends_on:
    - wordpress
  build: ./nginx
  image: nginx:notlatest
  env_file: .env
  volumes:
    - wordpress:/var/www/wordpress
  restart: always
  ports:
   - "443:443"